//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1611061593_lab3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_News
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<int> CateId { get; set; }
    }
}
